--- !ruby/object:StatisticsResult
name: Player5
hints: 2
attempts: 14
level: easy
all_attempts: 15
--- !ruby/object:StatisticsResult
name: Player6
hints: 2
attempts: 13
level: easy
all_attempts: 15
--- !ruby/object:StatisticsResult
name: Player7
hints: 1
attempts: 13
level: easy
all_attempts: 15
--- !ruby/object:StatisticsResult
name: Player3
hints: 1
attempts: 9
level: medium
all_attempts: 10
--- !ruby/object:StatisticsResult
name: Player4
hints: 0
attempts: 9
level: medium
all_attempts: 10
--- !ruby/object:StatisticsResult
name: Player1
hints: 1
attempts: 1
level: hell
all_attempts: 5
--- !ruby/object:StatisticsResult
name: Player2
hints: 0
attempts: 1
level: hell
all_attempts: 5
