--- !ruby/object:StatisticsResult
name: Player5
left_hints: 2
left_attempts: 14
level: easy
all_attempts: 15
all_hints: 2
--- !ruby/object:StatisticsResult
name: Player6
left_hints: 2
left_attempts: 13
level: easy
all_attempts: 15
all_hints: 2
--- !ruby/object:StatisticsResult
name: Player7
left_hints: 1
left_attempts: 13
level: easy
all_attempts: 15
all_hints: 2
--- !ruby/object:StatisticsResult
name: Player3
left_hints: 1
left_attempts: 9
level: medium
all_attempts: 10
all_hints: 1
--- !ruby/object:StatisticsResult
name: Player4
left_hints: 0
left_attempts: 9
level: medium
all_attempts: 10
all_hints: 1
--- !ruby/object:StatisticsResult
name: Player1
left_hints: 1
left_attempts: 1
level: hell
all_attempts: 5
all_hints: 1
--- !ruby/object:StatisticsResult
name: Player2
left_hints: 0
left_attempts: 1
level: hell
all_attempts: 5
all_hints: 1
